In [26]:
import numpy as np

1) Создайте двумерный массив 10x3, заполненный случайными значениями. В каждой строке выберите значение, наиболее близкое к 0.5.

In [33]:
a=np.random.random((10,3))
print(a)
[a[i,np.argmin(np.abs(a[i,:]-0.5))] for i in range(10)]

[[0.76589283 0.28082355 0.42113637]
 [0.55089907 0.77434734 0.72975126]
 [0.59419342 0.26076759 0.17148389]
 [0.04191553 0.96156358 0.37992664]
 [0.74330585 0.63532146 0.59786584]
 [0.92636613 0.15791141 0.47301454]
 [0.76788098 0.41462841 0.6826077 ]
 [0.3648652  0.22583314 0.99728915]
 [0.12878495 0.25078157 0.48355234]
 [0.71977803 0.43250464 0.78249061]]


[0.42113636957339884,
 0.5508990725503181,
 0.5941934247184677,
 0.3799266414563861,
 0.5978658358398895,
 0.47301453693252205,
 0.414628405019409,
 0.36486520404822786,
 0.48355233758547345,
 0.43250463594431876]

2) Создайте двумерный массив 6x6, заполненный случайными значениями. Затем сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом.

In [35]:
a=np.random.random((6,6))
print(a)
[np.sum(a[j,:])/np.min(a[:,j]) for j in range(6)]

[[0.65427098 0.81011025 0.23918205 0.22735318 0.22224496 0.09723644]
 [0.66140435 0.60094884 0.16557479 0.8694503  0.78981022 0.59039995]
 [0.83036877 0.27363902 0.54554332 0.01342752 0.47988156 0.31405564]
 [0.52077989 0.91027375 0.00980768 0.58652709 0.09840181 0.41218274]
 [0.30795906 0.16518028 0.35769667 0.47574049 0.0764238  0.93208711]
 [0.85351982 0.68556176 0.43245434 0.2558265  0.28095811 0.76686808]]


[7.307457922504764,
 22.26408942311902,
 250.50939413803667,
 189.01280326703431,
 30.29275461178182,
 33.68272969590056]

3) На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [49]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
s= [x[i] for i in range(1,9) if x[i-1]==0]
np.max(s)

5

4) Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [54]:
x = np.ones(10) 
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for k in i:
    x[k]=x[k]+1 
print (x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


5) Написать функцию, реализующую алгоритм k-means. Входные и выходные значения функции должны быть аналогичны https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.cluster.vq.kmeans.html. Функция должна содержать не более двух циклов while (for).